# Generated by Django 6.0.7 on 2026-07-28 22:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('nom_local', models.CharField(blank=True, max_length=150)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('origine', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='aliments/')),
                ('portion_standard_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('calories', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('proteines', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('glucides', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lipides', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fibres', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sodium_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sucres', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('graisses_saturees', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('potassium_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('index_glycemique', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('allergenes', models.CharField(blank=True, help_text='Liste séparée par des virgules, ex: arachide,lait', max_length=255)),
                ('niveau_confiance', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé')], default='moyen', max_length=20)),
                ('source_donnee', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RegleNutritionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(help_text='Ex: R01', max_length=10, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('niveau_alerte', models.CharField(choices=[('info', '🟢 Info'), ('vigilance', '🟡 Vigilance'), ('risque_eleve', '🔴 Risque élevé')], max_length=20)),
                ('message', models.TextField()),
                ('reference_scientifique', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('retiree', 'Retirée')], default='brouillon', max_length=20)),
                ('date_validation', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autre / non précisé')], max_length=1)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('langue', models.CharField(default='fr', max_length=10)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('utilisateur', 'Utilisateur'), ('nutritionniste', 'Nutritionniste'), ('dieteticien', 'Diététicien'), ('medecin', 'Médecin'), ('administrateur', 'Administrateur'), ('comite_scientifique', 'Comité scientifique')], default='utilisateur', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AllergieUtilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergene', models.CharField(max_length=100)),
                ('gravite', models.CharField(blank=True, max_length=100)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PathologieUtilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pathologie', models.CharField(max_length=150)),
                ('date_declaration', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(blank=True, max_length=50)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathologies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilSante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taille_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('poids_actuel_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('poids_cible_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('niveau_activite_physique', models.CharField(blank=True, choices=[('sedentaire', 'Sédentaire'), ('leger', 'Léger'), ('modere', 'Modéré'), ('intense', 'Intense')], max_length=20)),
                ('objectif_nutritionnel', models.CharField(blank=True, choices=[('perte_poids', 'Perte de poids'), ('maintien', 'Maintien'), ('prise_masse', 'Prise de masse'), ('equilibre', 'Équilibre alimentaire'), ('suivi_medical', 'Suivi médical')], max_length=20)),
                ('grossesse', models.BooleanField(default=False)),
                ('allaitement', models.BooleanField(default=False)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_sante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('type_repas', models.CharField(choices=[('petit_dejeuner', 'Petit-déjeuner'), ('dejeuner', 'Déjeuner'), ('diner', 'Dîner'), ('collation', 'Collation')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='repas/')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-heure'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('resolue', 'Résolue'), ('ignoree', 'Ignorée')], default='active', max_length=20)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL)),
                ('regle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.reglenutritionnelle')),
                ('repas', models.ForeignKey(blank=True, help_text="Repas ayant déclenché l'alerte, si applicable", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.repas')),
            ],
            options={
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='RepasAliment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.aliment')),
                ('repas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliments_consommes', to='core.repas')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_score', models.CharField(choices=[('alimentaire', 'Score alimentaire'), ('activite', 'Score activité'), ('evolution_corporelle', 'Score évolution corporelle'), ('indice_fiabilite', 'Indice de fiabilité')], max_length=30)),
                ('valeur', models.DecimalField(decimal_places=1, max_digits=5)),
                ('date_calcul', models.DateField(auto_now_add=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.CreateModel(
            name='TraitementUtilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicament', models.CharField(max_length=150)),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('frequence', models.CharField(blank=True, max_length=100)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
