# Generated by Django 6.0.7 on 2026-08-05 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aliment_vitamine_k_mcg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialite', models.CharField(choices=[('medecin_generaliste', 'Médecin généraliste'), ('nutritionniste', 'Nutritionniste'), ('dieteticien', 'Diététicien'), ('cardiologue', 'Cardiologue'), ('endocrinologue', 'Endocrinologue (diabète, thyroïde...)'), ('nephrologue', 'Néphrologue'), ('autre', 'Autre spécialité')], max_length=30)),
                ('specialite_autre', models.CharField(blank=True, help_text="Si 'Autre spécialité' est sélectionné ci-dessus.", max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Présentation courte visible par les patients.')),
                ('numero_autorisation', models.CharField(blank=True, help_text="Numéro d'autorisation d'exercer (renforce la confiance, vérifié par l'administrateur).", max_length=100)),
                ('verifie', models.BooleanField(default=False)),
                ('accepte_teleconsultation', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_professionnel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('type_rendezvous', models.CharField(choices=[('presentiel', 'Présentiel'), ('teleconsultation', 'Téléconsultation (vidéo)')], max_length=20)),
                ('statut', models.CharField(choices=[('demande', 'Demande envoyée'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='demande', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_en_tant_que_patient', to=settings.AUTH_USER_MODEL)),
                ('professionnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_recus', to='core.professionnel')),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
    ]
